trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: 'MyAzureConnection_SPA'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account list-locations --query "[].{Region:name}" --out table'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'MyAzureConnection_SPA'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create  --name cross_tenant_test_rg  --location northeurope'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'MyAzureConnection_SPA'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage account create --name crosstenanttestsa --resource-group cross_tenant_test_rg --location northeurope --sku Standard_LRS --kind StorageV2'
    
- task: AzureCLI@1
  inputs:
    azureSubscription: 'MyAzureConnection_SPA'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group delete --name cross_tenant_test_rg'
